### ISSUE TITLE
[Plugin] update PluginInterface and PluginManager

### ISSUE THREAD

**Issue by eric-chau** [backbee/ToolbarBundle#12]
I exchange about plugin configuration with @hbaptiste and we end up with this result:

```json
{
    "plugin": {
        "namespace": {
            "core": "/path/to/your/test/plugin/src"
        },
        "core": {
            "contentselector": {
                "foo": "bar"
            },
            "toyellow": {
                "accept": [
                    "BackBee\\ClassContent\\Element\\text",
                    "BackBee\\ClassContent\\article"
                ]
            }
        }
    }
}
```

Note that we cannot have a namespace called ``namespace``.

PluginInterface must be updated to be more specific and PluginManager must be updated too.

**Comment by mickaelandrieu** [comment]
Hi @eric-chau,
can you list what do we have to do in ``backbee\BackBee`` ?

**Comment by eric-chau** [comment]
Hi @mickaelandrieu,
there is nothing to do on ``backbee/backbee`` since ``PluginInterface`` and ``PluginManager`` come with ``backbee/toolbar-bundle``.
